- name: create ec2 and r53
  hosts: all
  connection : local
  vars:
    sg_id: sg-01cf16e6da2a69f8b
    ami_id: ami-0220d79f3f480ecf5
    domain_name: aws.roboshop.online
    env: dev
    instances:
      - mongodb
      - catalogue
  tasks: 
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      name: "{{ item }} - {{ env }}"
      tags: 
        Project: ansible roboshop
        Component: "{{ item }}"
        Environment: "{{ env }}"
        Name: "{{ item }} -{{ env }}"
    loop: "{{ instances }}"
    register: ec2_output
  
  - name: print the ec2_output
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item}}-{{ env }}.{{ domain_name}}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ ec2_output.results }}"
    